// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpvljqkcrwnusnmclurr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdmxqcWtjcndudXNubWNsdXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTMzNTIsImV4cCI6MjA2Mjc4OTM1Mn0.0lFx-34l7Es47JWZIiggNoeulpq3Fu7uOmNHnSaMFGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);